export const PLAYER_HEALTH_CHANGED = 'PLAYER_HEALTH_CHANGED';
export const PLAYER_COINS_CHANGED = 'PLAYER_COINS_CHANGED';
export const PLAYER_ENERGY_CHANGED = 'PLAYER_ENERGY_CHANGED';
export const GAME_LOADED = 'GAME_LOADED';
export const PLAYER_DEAD = 'PLAYER_DEAD';
